steps:
- name: 'gcr.io/cloud-builders/npm:node-8.9.3'
  args: ['install']
  id: step1
- name: 'gcr.io/cloud-builders/npm:node-8.9.3'
  args: ['run-script', 'build']
  id: build
#- name: 'gcr.io/fintend-cloud/update-nginx-resource:v1.0.3'
#  id: deploy_nginx_resource
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ethex-frontend:$COMMIT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/kubectl'
  args: [ 'apply', '-f', 'cloudbuild.yaml', '-l', 'myapp=gcr.io/$PROJECT_ID/ethex-frontend:$COMMIT_SHA' ]

#  - set
#  - image
#  - deployment
#  - webapp3
#  - webapp3=gcr.io/$PROJECT_ID/ethex-frontend:$COMMIT_SHA
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-test'
  id: deploy-k8s
images:
- 'gcr.io/$PROJECT_ID/ethex-frontend:$COMMIT_SHA'
timeout: '3600s'
substitutions:
  #  _DEPLOY_URL: "https://static.coinpool.com/resource/dist"
  _DEPLOY_URL: ""
options:
  machineType: 'N1_HIGHCPU_8'
